### PR TITLE
Change license from MIT to AGPLv3

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
The MIT license is horrible, please, let's use a GOOD license

### CODE REVIEW

**Comment by Jimmysit0** [comment]
https://github.com/rose-pine/rose-pine-theme/pull/51#issuecomment-958976404

**Comment by mvllow** [comment]
Don’t know too much about licenses. Does this new license require any attribution? I prefer whatever is easiest and least invasive for someone wanting to use our code. Open to all 😌

**Comment by ThatOneCalculator** [comment]
> Don’t know too much about licenses. Does this new license require any attribution? I prefer whatever is easiest and least invasive for someone wanting to use our code. Open to all relieved

It would require attribution, given its copyleft nature

**Comment by mvllow** [comment]
I'm a little confused on why MIT is so bad here. Other big themes are also using MIT and it seems like a user-focused license, allowing modifications and redistribution without needing our permission.

**Comment by Jimmysit0** [comment]
I think MIT is fine, and I still don't know why @ThatOneCalculator finds it bad, even after my comment :confused:

**Pull request closed without merging**
