### PR TITLE
Add badges

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
This will add badges to all the repos in the readme which shows which themes they have available. I also created the Rosé Pine Moon & Dawn icons to match the main one.

Screenshot_2021-11-23-10-05-44_2560x1440

### CODE REVIEW

**Comment by Jimmysit0** [comment]
I think the idea is fine, but I don't really like having 3 badges on a single repo - Maybe we can have a single badge that means that it has all the palette "variations"? That said, the screenshot you sent isn't really accurate, as some repos do have more than the base palette, but I get that it could be a simple example.

**Comment by mvllow** [comment]
How do we feel about this for a dark/light badge?

**Comment by ThatOneCalculator** [comment]
> I think the idea is fine, but I don't really like having 3 badges on a single repo - Maybe we can have a single badge that means that it has all the palette "variations"? That said, the screenshot you sent isn't really accurate, as some repos do have more than the base palette, but I get that it could be a simple example.

The screenshot is accurate, it's what's in the PR. I went through and checked each repo.

**Comment by ThatOneCalculator** [comment]
> How do we feel about this for a dark/light badge?
> 
> 

Would that badge indicate that a repo has all themes?

**Comment by Jimmysit0** [comment]
> > I think the idea is fine, but I don't really like having 3 badges on a single repo - Maybe we can have a single badge that means that it has all the palette "variations"? That said, the screenshot you sent isn't really accurate, as some repos do have more than the base palette, but I get that it could be a simple example.
> 
> The screenshot is accurate, it's what's in the PR. I went through and checked each repo.

Nope, just as an example, the Emacs repo has all the themes. Many others such as termite do too.

**Comment by mvllow** [comment]
> Would that badge indicate that a repo has all themes?

At least a dark & light variant. I'm not too concerned about which dark variant. Could be all 3 variants or 2 if one is dawn.

**Comment by ThatOneCalculator** [comment]
> > Would that badge indicate that a repo has all themes?
> 
> At least a dark & light variant. I'm not too concerned about which dark variant. Could be all 3 variants or 2 if one is dawn.

sounds good. your badge looks really good, here's my idea as well. which do you prefer? 
combo_icon

**Comment by mvllow** [comment]
I think the more neutral version will be more readable at small sizes, especially the badge size 😌 I played around with the split backgrounds too and it's hard to balance

**Comment by mvllow** [comment]
Just having fun now

rp-mixed-colour

**Comment by Jimmysit0** [comment]
I really like what @mvllow just sent, and imo it looks way better. We should consider using this badge instead

**Comment by ThatOneCalculator** [comment]
I love that badge too!!

**Comment by ThatOneCalculator** [comment]
Gonna close this and reopen with a new version with fversts's badge

**Pull request closed without merging**
